### ISSUE TITLE
How can I add a network app to ctrlx and add a menu item to slider

### ISSUE THREAD

**Issue by LelandACM** [boschrexroth/ctrlx-automation-sdk#34]
## enviroment
sdk: the latest version
ctrl works: ctrlX WORKS WRK-V-0120.5
## node js version
node: 18.18.2
npm: 10.2.3

I added a samples-vue to the ctrlx-automation-sdk directory。
I builded the script `build-snap-amd64.sh` 

## my snapcraft.yaml config
```
# See https://snapcraft.io/docs/getting-started
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: vue
version: '1.0.1'
base: core20
title: vue
summary: samples-vue for ctrlX
description: |
  samples-vue apps.
grade: stable         # must be 'stable' to release into candidate/stable channels
confinement: strict   # reduced file access to selected areas, reduced

parts:
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

  vue:
    source: .
    plugin: npm
    npm-node-version: '16.15.1'
    override-build: |
      # install node
      snapcraftctl build

      # install dependencies
      npm install

      # run vuejs build script
      npm run build

      # remove node
      rm -rf ${SNAPCRAFT_PART_INSTALL}
    organize:
      '${SNAPCRAFT_PART_BUILD}/dist/app': vue/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

  vue:
    interface: content
    content: vue
    source:
      read:
      - $SNAP/vue/${SNAPCRAFT_PROJECT_NAME}
```

my manifest.json config is:
```
{
  "$schema": "https://json-schema.boschrexroth.com/ctrlx-automation/ctrlx-core/apps/package-manifest/package-manifest.v1.3.schema.json",
  "version": "1.0.0",
  "id": "vue",
  "menus": {
    "sidebar": [
      {
        "id": "vue",
        "title": "vue",
        "icon": "bosch-ic-translate",
        "items": [
          {
            "id": "vue",
            "title": "ctrlX",
            "target": "_blank",
            "link": "/vue"
          }
        ]
      }
    ]
  }
}
```
the refs url is: https://github.com/LelandACM/ctrlx-automation-sdk/tree/main/samples-vue

I builded a snap file and upload to app store, but open the router, tips: Page 404 not found
![20231229174309](https://github.com/boschrexroth/ctrlx-automation-sdk/assets/19402747/6529324a-0b60-464a-a218-6b18924a1171)
